version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            - dependencies-cache
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      - run:
          name: Run Tests with Coverage
          command: |
            # ./cc-test-reporter before-build
            npm test
            # ./cc-test-reporter after-build --exit-code $?
workflows:
  version: 2
  package-workflow:
    jobs:
      - build